name: Laravel Workflow
on: push


jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-18.04    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Composer
        uses: ./.github/actions/composer     
