name: Laravel Workflow
on: push


jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-18.04    
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ./.github/actions/composer
