name: Laravel Workflow
on: push
jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-18.04           
      steps:      
        - run: actions/checkout@v1      
        - run: ./.github/actions/composer
