name: Laravel Workflow
on: push


jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-18.04    
    steps:      
       - uses: actions/checkout@v1      
      #  - uses: ./.github/actions/composer    
       - run:  chmod +x ./.github/actions/composer/entrypoint.sh
       - run: ./.github/actions/composer/entrypoint.sh
       - run:  chmod +x ./.github/actions/config-laravel/entrypoint.sh
       - run: ./.github/actions/config-laravel/entrypoint.sh       
