name: Laravel Workflow
on: push
jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-18.04           
      steps:      
        - name: Checkout code
          uses: actions/checkout@v2   
        - name: Installing composer 
          uses: ./.github/actions/composer
